name: soaocr
favicon: null
layout_spectrum: 0.34808215335942805
typography_spectrum: 0.8006732736248523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.980763416737318
  lightness: 0.29902962292544544
  saturation: 0.7174289969261736
  rhythmicContrast: 0.20967653370462358
purpose: []
